Repository 2Tiny2Scale/ScaleTail, pull requests merged in 2024-12, with the labels that each got.

#28 Change to template - Environment Variables / Parameterized the template
  templates/service-template/.env
  templates/service-template/README.md
  templates/service-template/config/serve.json
  templates/service-template/docker-compose.yml
Labels: enhancement

#31 Fixed issue
  templates/service-template/.env
  templates/service-template/docker-compose.yml
Labels: bug

#32 Added Gokapi
  README.md
  services/gokapi/.env
  services/gokapi/README.md
  services/gokapi/config/serve.json
  services/gokapi/docker-compose.yml
Labels: new content

#35 Added IT-Tools
  README.md
  services/it-tools/.env
  services/it-tools/README.md
  services/it-tools/config/serve.json
  services/it-tools/docker-compose.yml
Labels: new content

#33 Added Dozzle
  README.md
  services/dozzle/.env
  services/dozzle/README.md
  services/dozzle/config/serve.json
  services/dozzle/docker-compose.yml
  services/dozzle/dozzle-data/users.yml
Labels: new content

#34 Added Cyberchef
  README.md
  services/cyberchef/.env
  services/cyberchef/README.md
  services/cyberchef/config/serve.json
  services/cyberchef/docker-compose.yml
Labels: new content

#38 Added Pingvin-Share
  README.md
  services/pingvin-share/.env
  services/pingvin-share/README.md
  services/pingvin-share/config/serve.json
  services/pingvin-share/docker-compose.yml
Labels: new content

#39 Added Markdown Checking
  .github/workflows/linting.yml
  .markdownlint.yml
  services/jellyfin/README.md
  services/languagetool/README.md
Labels: enhancement

#37 Traefik added
  README.md
  services/traefik/.env
  services/traefik/README.md
  services/traefik/config/serve.json
  services/traefik/docker-compose.yml
  services/traefik/traefik/app/traefik.yml
Labels: new content

#40 Move existing services to .env
  services/adguardhome/.env
  services/adguardhome/docker-compose.yml
  services/bazarr/.env
  services/bazarr/docker-compose.yml
  services/beszel/agent/.env
  services/beszel/agent/docker-compose.yml
  services/beszel/hub/.env
  services/beszel/hub/docker-compose.yml
  services/excalidraw/.env
  services/excalidraw/docker-compose.yml
  services/homarr/.env
  services/homarr/docker-compose.yml
  services/jellyfin/.env
  services/jellyfin/docker-compose.yml
  services/languagetool/.env
  services/languagetool/docker-compose.yml
  services/nextcloud/.env
  services/nextcloud/docker-compose.yml
  services/pihole/.env
  services/pihole/docker-compose.yml
  services/plex/.env
  services/plex/docker-compose.yml
  services/portainer/.env
  services/portainer/docker-compose.yml
  services/qbittorrent/.env
  services/qbittorrent/docker-compose.yml
  services/radarr/.env
  services/radarr/docker-compose.yml
  services/resilio-sync/.env
  services/resilio-sync/docker-compose.yml
  services/searxng/.env
  services/searxng/docker-compose.yml
  services/sonarr/.env
  services/sonarr/docker-compose.yml
  services/stirlingpdf/.env
  services/stirlingpdf/docker-compose.yml
  services/tailscale-exit-node/.env
  services/tailscale-exit-node/docker-compose.yml
  services/tautulli/.env
  services/tautulli/docker-compose.yml
  services/uptime-kuma/.env
  services/uptime-kuma/docker-compose.yml
  services/vaultwarden/.env
  services/vaultwarden/docker-compose.yml
Labels: enhancement

#42 Update README.md
  .github/workflows/linting.yml
  README.md
Labels: enhancement

#43 Refactor README.md
  README.md
Labels: enhancement

#45 Added Slink
  README.md
  services/slink/.env
  services/slink/README.md
  services/slink/config/serve.json
  services/slink/docker-compose.yml
Labels: new content
