Repository 2Tiny2Scale/ScaleTail, pull requests merged in 2025-01, with the labels that each got.

#44 Improved tailscale healthcheck
  services/adguardhome/docker-compose.yml
  services/bazarr/docker-compose.yml
  services/beszel/agent/docker-compose.yml
  services/beszel/hub/docker-compose.yml
  services/changedetection/docker-compose.yml
  services/cyberchef/docker-compose.yml
  services/dozzle/docker-compose.yml
  services/excalidraw/docker-compose.yml
  services/gokapi/docker-compose.yml
  services/homarr/docker-compose.yml
  services/it-tools/docker-compose.yml
  services/jellyfin/docker-compose.yml
  services/languagetool/docker-compose.yml
  services/nextcloud/docker-compose.yml
  services/nodered/docker-compose.yml
  services/pihole/docker-compose.yml
  services/pingvin-share/docker-compose.yml
  services/plex/docker-compose.yml
  services/portainer/docker-compose.yml
  services/qbittorrent/docker-compose.yml
  services/radarr/docker-compose.yml
  services/resilio-sync/docker-compose.yml
  services/searxng/docker-compose.yml
  services/sonarr/docker-compose.yml
  services/stirlingpdf/docker-compose.yml
  services/tailscale-exit-node/docker-compose.yml
  services/tautulli/docker-compose.yml
  services/technitium/docker-compose.yml
  services/traefik/docker-compose.yml
  services/uptime-kuma/docker-compose.yml
  services/vaultwarden/docker-compose.yml
  templates/service-template/docker-compose.yml
Labels: enhancement

#47 Added DDNS-updater
  README.md
  services/ddns-updater/.env
  services/ddns-updater/README.md
  services/ddns-updater/config/serve.json
  services/ddns-updater/docker-compose.yml
Labels: new content

#46 Added Isley
  README.md
  services/isley/.env
  services/isley/README.md
  services/isley/config/serve.json
  services/isley/docker-compose.yml
Labels: new content

#49 Issue and PR templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: new content

#48 Enhance Service Dependency with Healthcheck Condition
  services/adguardhome/docker-compose.yml
  services/bazarr/docker-compose.yml
  services/beszel/agent/docker-compose.yml
  services/beszel/hub/docker-compose.yml
  services/changedetection/docker-compose.yml
  services/cyberchef/docker-compose.yml
  services/ddns-updater/docker-compose.yml
  services/dozzle/docker-compose.yml
  services/excalidraw/docker-compose.yml
  services/gokapi/docker-compose.yml
  services/homarr/docker-compose.yml
  services/isley/docker-compose.yml
  services/it-tools/docker-compose.yml
  services/jellyfin/docker-compose.yml
  services/languagetool/docker-compose.yml
  services/nextcloud/docker-compose.yml
  services/nodered/docker-compose.yml
  services/pihole/docker-compose.yml
  services/pingvin-share/docker-compose.yml
  services/plex/docker-compose.yml
  services/portainer/docker-compose.yml
  services/qbittorrent/docker-compose.yml
  services/radarr/docker-compose.yml
  services/resilio-sync/docker-compose.yml
  services/searxng/docker-compose.yml
  services/slink/docker-compose.yml
  services/sonarr/docker-compose.yml
  services/stirlingpdf/docker-compose.yml
  services/tautulli/docker-compose.yml
  services/technitium/docker-compose.yml
  services/traefik/docker-compose.yml
  services/uptime-kuma/docker-compose.yml
  services/vaultwarden/docker-compose.yml
  templates/service-template/docker-compose.yml
Labels: enhancement

#50 Consistent Variable Naming
  services/technitium/.env
  services/technitium/docker-compose.yml
Labels: enhancement

#53 Fix for tstun.New("tailscale0"): operation not permitted
  services/adguardhome/docker-compose.yml
  services/bazarr/docker-compose.yml
  services/beszel/agent/docker-compose.yml
  services/beszel/hub/docker-compose.yml
  services/changedetection/docker-compose.yml
  services/cyberchef/docker-compose.yml
  services/ddns-updater/docker-compose.yml
  services/dozzle/docker-compose.yml
  services/excalidraw/docker-compose.yml
  services/gokapi/docker-compose.yml
  services/homarr/docker-compose.yml
  services/isley/docker-compose.yml
  services/it-tools/docker-compose.yml
  services/jellyfin/docker-compose.yml
  services/languagetool/docker-compose.yml
  services/nextcloud/docker-compose.yml
  services/nodered/docker-compose.yml
  services/pihole/docker-compose.yml
  services/pingvin-share/docker-compose.yml
  services/plex/docker-compose.yml
  services/portainer/docker-compose.yml
  services/qbittorrent/docker-compose.yml
  services/radarr/docker-compose.yml
  services/resilio-sync/docker-compose.yml
  services/searxng/docker-compose.yml
  services/slink/docker-compose.yml
  services/sonarr/docker-compose.yml
  services/stirlingpdf/docker-compose.yml
  services/tailscale-exit-node/docker-compose.yml
  services/tautulli/docker-compose.yml
  services/technitium/docker-compose.yml
  services/traefik/docker-compose.yml
  services/uptime-kuma/docker-compose.yml
  services/vaultwarden/docker-compose.yml
Labels: bug

#55 Resolved interpretation issue for TS_AUTHKEY
  services/adguardhome/.env
  services/bazarr/.env
  services/beszel/agent/.env
  services/beszel/hub/.env
  services/changedetection/.env
  services/cyberchef/.env
  services/ddns-updater/.env
  services/dozzle/.env
  services/excalidraw/.env
  services/gokapi/.env
  services/homarr/.env
  services/isley/.env
  services/it-tools/.env
  services/jellyfin/.env
  services/languagetool/.env
  services/nextcloud/.env
  services/nodered/.env
  services/pihole/.env
  services/pingvin-share/.env
  services/plex/.env
  services/portainer/.env
  services/qbittorrent/.env
  services/radarr/.env
  services/resilio-sync/.env
  services/searxng/.env
  services/slink/.env
  services/sonarr/.env
  services/stirlingpdf/.env
  services/tailscale-exit-node/.env
  services/tautulli/.env
  services/technitium/.env
  services/traefik/.env
  services/uptime-kuma/.env
  services/vaultwarden/.env
Labels: bug

#54 Removed double use of devices
  services/tailscale-exit-node/docker-compose.yml
Labels: bug

#57 Fixing PATH issue for Serve
  services/adguardhome/docker-compose.yml
  services/bazarr/docker-compose.yml
  services/beszel/agent/docker-compose.yml
  services/beszel/hub/docker-compose.yml
  services/changedetection/docker-compose.yml
  services/cyberchef/docker-compose.yml
  services/ddns-updater/docker-compose.yml
  services/dozzle/docker-compose.yml
  services/excalidraw/docker-compose.yml
  services/gokapi/docker-compose.yml
  services/homarr/docker-compose.yml
  services/isley/docker-compose.yml
  services/it-tools/docker-compose.yml
  services/jellyfin/docker-compose.yml
  services/languagetool/docker-compose.yml
  services/nextcloud/docker-compose.yml
  services/nodered/docker-compose.yml
  services/pihole/docker-compose.yml
  services/pingvin-share/docker-compose.yml
  services/plex/docker-compose.yml
  services/portainer/docker-compose.yml
  services/qbittorrent/docker-compose.yml
  services/radarr/docker-compose.yml
  services/resilio-sync/docker-compose.yml
  services/searxng/docker-compose.yml
  services/slink/docker-compose.yml
  services/sonarr/docker-compose.yml
  services/stirlingpdf/docker-compose.yml
  services/tailscale-exit-node/docker-compose.yml
  services/tautulli/docker-compose.yml
  services/technitium/README.md
  services/technitium/docker-compose.yml
  services/uptime-kuma/docker-compose.yml
  services/vaultwarden/docker-compose.yml
  templates/service-template/docker-compose.yml
Labels: bug

#58 Added Audiobookshelf
  README.md
  services/audiobookshelf/.env
  services/audiobookshelf/README.md
  services/audiobookshelf/config/serve.json
  services/audiobookshelf/docker-compose.yml
Labels: new content

#60 Update Service Template
  templates/service-template/.env
Labels: enhancement

#61 Added Linkding
  README.md
  services/linkding/.env
  services/linkding/.linkding.env
  services/linkding/README.md
  services/linkding/config/serve.json
  services/linkding/docker-compose.yml
Labels: new content

#63 Updated Title README.md
  README.md
Labels: enhancement

#64 Unnecessary-folder in volumes
  services/adguardhome/docker-compose.yml
  services/audiobookshelf/docker-compose.yml
  services/bazarr/docker-compose.yml
  services/beszel/agent/docker-compose.yml
  services/beszel/hub/docker-compose.yml
  services/changedetection/docker-compose.yml
  services/clipcascade/docker-compose.yml
  services/cyberchef/docker-compose.yml
  services/ddns-updater/docker-compose.yml
  services/dozzle/docker-compose.yml
  services/excalidraw/docker-compose.yml
  services/gokapi/docker-compose.yml
  services/homarr/docker-compose.yml
  services/isley/docker-compose.yml
  services/it-tools/docker-compose.yml
  services/jellyfin/docker-compose.yml
  services/languagetool/docker-compose.yml
  services/linkding/docker-compose.yml
  services/nextcloud/docker-compose.yml
  services/nodered/docker-compose.yml
  services/pihole/docker-compose.yml
  services/pingvin-share/docker-compose.yml
  services/plex/docker-compose.yml
  services/portainer/docker-compose.yml
  services/qbittorrent/docker-compose.yml
  services/radarr/docker-compose.yml
  services/resilio-sync/docker-compose.yml
  services/searxng/docker-compose.yml
  services/slink/docker-compose.yml
  services/sonarr/docker-compose.yml
  services/stirlingpdf/docker-compose.yml
  services/tailscale-exit-node/docker-compose.yml
  services/tautulli/docker-compose.yml
  services/technitium/docker-compose.yml
  services/uptime-kuma/docker-compose.yml
  services/vaultwarden/docker-compose.yml
  templates/service-template/docker-compose.yml
Labels: enhancement

#67 Added Speedtest-Tracker
  README.md
  services/speedtest-tracker/.env
  services/speedtest-tracker/README.md
  services/speedtest-tracker/config/serve.json
  services/speedtest-tracker/docker-compose.yml
  services/speedtest-tracker/nginx/default.conf
Labels: new content

#68 Updated container name for Tailscale
  services/adguardhome/docker-compose.yml
  services/audiobookshelf/docker-compose.yml
  services/bazarr/docker-compose.yml
  services/beszel/agent/docker-compose.yml
  services/beszel/hub/docker-compose.yml
  services/changedetection/docker-compose.yml
  services/clipcascade/docker-compose.yml
  services/cyberchef/docker-compose.yml
  services/ddns-updater/docker-compose.yml
  services/dozzle/docker-compose.yml
  services/excalidraw/docker-compose.yml
  services/gokapi/docker-compose.yml
  services/homarr/docker-compose.yml
  services/isley/docker-compose.yml
  services/it-tools/docker-compose.yml
  services/jellyfin/docker-compose.yml
  services/languagetool/docker-compose.yml
  services/linkding/docker-compose.yml
  services/nextcloud/docker-compose.yml
  services/nodered/docker-compose.yml
  services/pihole/docker-compose.yml
  services/pingvin-share/docker-compose.yml
  services/plex/docker-compose.yml
  services/portainer/docker-compose.yml
  services/qbittorrent/docker-compose.yml
  services/radarr/docker-compose.yml
  services/resilio-sync/docker-compose.yml
  services/searxng/docker-compose.yml
  services/slink/docker-compose.yml
  services/sonarr/docker-compose.yml
  services/stirlingpdf/docker-compose.yml
  services/tailscale-exit-node/docker-compose.yml
  services/tautulli/docker-compose.yml
  services/technitium/docker-compose.yml
  services/traefik/docker-compose.yml
  services/uptime-kuma/docker-compose.yml
  services/vaultwarden/docker-compose.yml
  templates/service-template/docker-compose.yml
Labels: enhancement

#69 Fix: Health check for Isley placed under devices section.
  services/isley/docker-compose.yml
Labels: bug

#71 Added Tenable Nessus
  README.md
  services/nessus/.env
  services/nessus/README.md
  services/nessus/config/serve.json
  services/nessus/docker-compose.yml
Labels: new content

#75 Added Home-Assistant
  README.md
  services/home-assistant/.env
  services/home-assistant/README.md
  services/home-assistant/config/serve.json
  services/home-assistant/docker-compose.yml
Labels: new content
