Repository 2Tiny2Scale/ScaleTail, pull requests merged in 2025-08, with the labels that each got.

#128 Added Wallos
  README.md
  services/wallos/.env
  services/wallos/README.md
  services/wallos/config/serve.json
  services/wallos/docker-compose.yml
Labels: new content

#132 Added fix for correct IP
  services/copyparty/config/copyparty.conf
Labels: bug

#133 Added Gramps Web
  README.md
  services/grampsweb/.env
  services/grampsweb/README.md
  services/grampsweb/config/serve.json
  services/grampsweb/docker-compose.yml
Labels: new content

#134 Added Subtrackr
  README.md
  services/subtrackr/.env
  services/subtrackr/README.md
  services/subtrackr/config/serve.json
  services/subtrackr/docker-compose.yml
Labels: new content

#135 Updated Homarr to new standard
  services/homarr/.env
  services/homarr/docker-compose.yml
Labels: enhancement
